.catalog:
  name: cassandra
  version: 0.10.0.0-rancher1
  description: |
    cassandra cluster.
  minimum_rancher_version: v0.59.0
  maintainer: "Pawan Kumar <monu.pawan@gmail.com>"
  uuid: cassandra-0
  questions:
    - variable: "cassandra_scale"
      description: "Number of cassandra nodes"
      label: "Cassandra Nodes:"
      required: true
      default: 3
      type: "int"
cass:
  scale: ${cassandra_scale}
  retain_ip: true
