Seed:
  tty: true
  restart: always
  ports:
  - 9042:9044/tcp
  - 9160:9106/tcp
  labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  volumes:
   - /usr/local/aeris_lib/resources/:/usr/local/aeris_lib/resources
   - /usr/local/aeris_lib/cassandra/:/usr/local/aeris_lib/cassandra
  environment:
    RANCHER_ENABLE: 'true'
    CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    JVMMEM: ${jvmmem}
    MAX_HEAP_SIZE: ${maxheap}
    HEAP_NEWSIZE: ${heapsize}
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/cassandra-1.1.6:3
  command: bash /usr/local/cassandra/apache-cassandra-1.1.6/bin/start-cass-service.sh seed Seed ${seed_scale} ${cassandra_scale}
Peer:
  tty: true
  restart: always
  ports:
  - 9042:9044/tcp
  - 9160:9106/tcp
  labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  volumes:
   - /usr/local/aeris_lib/resources/:/usr/local/aeris_lib/resources
  environment:
    RANCHER_ENABLE: 'true'
    CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    JVMMEM: ${jvmmem}
    MAX_HEAP_SIZE: ${maxheap}
    HEAP_NEWSIZE: ${heapsize}
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/cassandra-1.1.6:3
  command: bash /usr/local/cassandra/apache-cassandra-1.1.6/bin/start-cass-service.sh peer Seed ${seed_scale} ${cassandra_scale}
  links: 
   - Seed:Seed
