.catalog:
  name: cassandra
  version: 0.10.0.0-rancher-cassandra-1.1.6
  description: |
    cassandra cluster 1.1.6
  minimum_rancher_version: v0.59.0
  maintainer: "Pawan Kumar <monu.pawan@gmail.com>"
  uuid: cassandra-0
  questions:
    - variable: "seed_scale"
      description: "Number of cassandra seed nodes"
      label: "Cassandra Seed Nodes:"
      required: true
      default: 2
      type: "int"
    - variable: "cassandra_scale"
      description: "Number of cassandra peer nodes"
      label: "Cassandra peer Nodes:"
      required: true
      default: 2
      type: "int"
    - variable: "jvmmem"
      description: "JVM Memory in Kb"
      label: "JVM Memory:"
      required: true
      default: 256
      type: "string"
    - variable: "maxheap"
      description: "Max Heap size in GB"
      label: "Max heap size:"
      required: true
      default: 12G
      type: "string"
    - variable: "heapsize"
      description: "Heap size in mb"
      label: "Heap size:"
      required: true
      default: 400M
      type: "string"
Seed:
  scale: ${seed_scale}
Peer:
  scale: ${cassandra_scale}
